// Test
/*Ray myray = new Ray();
		
		myray = Camera.main.ScreenPointToRay(Input.mousePosition);
		if (Physics.Raycast(myray, out hit, 500.0f))
		{
			print(hit.collider.name);
		}*/

//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:4.0.30319.34209
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class PlayerLooker
	{
		public PlayerLooker ()
		{
		}
	}
}

